/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import dao.UsuarioDao;
import java.util.Arrays;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author LENOVO
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    
    UsuarioDao usuarioDao;
    
    public TelaCadastro() {
        initComponents();
        usuarioDao = new UsuarioDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campo_cpf = new javax.swing.JFormattedTextField();
        campo_bancos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        campo_confirmaSenha = new javax.swing.JPasswordField();
        bt_cadastrar_user = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campo_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de caixa eletrônico");
        setMinimumSize(new java.awt.Dimension(420, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setText("BANCO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        campo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("NOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        try {
            campo_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_cpf.setToolTipText("");
        campo_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cpfActionPerformed(evt);
            }
        });
        getContentPane().add(campo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 230, 30));

        campo_bancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Itaú", "Bradesco", "Santander", "Banco do Brasil", "Nubank" }));
        campo_bancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_bancosActionPerformed(evt);
            }
        });
        getContentPane().add(campo_bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel4.setText("CPF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        campo_confirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_confirmaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_confirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, -1));

        bt_cadastrar_user.setText("CADASTRAR");
        bt_cadastrar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrar_userActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cadastrar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jLabel5.setText("CADASTRO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 40));

        jLabel6.setText("MAX:20");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setText("CONFIRME SUA SENHA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel8.setText("SENHA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, -1));

        pack();
    }// </editor-fold>                        

    private void campo_nomeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void campo_confirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        
    }                                                   

    private void bt_cadastrar_userActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
       
        // verifica se tem algum parametro invalido
        if(String.valueOf(campo_senha.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "O campo SENHA é obrigatório, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }
        
        else if(campo_cpf.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatório, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(campo_nome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo NOME é obrigatório, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(String.valueOf(campo_confirmaSenha.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "O campo CONFIRMAÇÂO DE SENHA é obrigatório, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(!(String.valueOf(campo_confirmaSenha.getPassword()).equals(String.valueOf(campo_senha.getPassword())))){
            JOptionPane.showMessageDialog(null, "Senhas inválidas, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }
        
        else{
            JOptionPane.showMessageDialog(null, "USUÁRIO CADASTRADO COM SUCESSO", 
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            //CADASTRANDO USUARIO
        
            Usuario novoUsuario = new Usuario();
        
                novoUsuario.setNome(campo_nome.getText());
                novoUsuario.setCpf(campo_cpf.getText());
                novoUsuario.setBanco(campo_bancos.getSelectedItem().toString());
            // ele pega a opcao selecionada em String?
                novoUsuario.setSenha(String.valueOf(campo_confirmaSenha.getPassword()));
        
        usuarioDao.cadastrar(novoUsuario);
        }
        
        
        
    }                                                 

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TelaLogin tLogin = new TelaLogin();
        tLogin.setVisible(true); // mostra a TelaCadastro
        this.dispose(); // fecha a tela de login
        
    }                                         

    private void campo_cpfActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void campo_bancosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_cadastrar_user;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JComboBox<String> campo_bancos;
    private javax.swing.JPasswordField campo_confirmaSenha;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration                   
}
