/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.UsuarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelLogin1 = new javax.swing.JLabel();
        labelLogin2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campo_senha = new javax.swing.JPasswordField();
        bt_cadastrar = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        campo_cpf = new javax.swing.JFormattedTextField();
        bt_entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIstema de caixa eletrônico");
        setMinimumSize(new java.awt.Dimension(430, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelLogin1.setText("CPF");
        getContentPane().add(labelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 10));

        labelLogin2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelLogin2.setText("SENHA");
        getContentPane().add(labelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 10));

        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jLabel1.setText("CAIXA 24 HORAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, 30));

        bt_cadastrar.setText("CADASTRAR");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        bt_sair.setText("SAIR");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 70, -1));

        try {
            campo_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, 30));

        bt_entrar.setText("ENTRAR");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Não possui uma conta?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        pack();
    }// </editor-fold>                        

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        TelaCadastro tCadastro = new TelaCadastro();
        tCadastro.setVisible(true); // mostra a TelaCadastro
        this.dispose(); // fecha a tela de login
    }                                            

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.out.println("\n--------------------------------\nDeveloped by: Joaquim Cabral\nMy GitHub: https://github.com/Joaquim-python3\n--------------------------------");
        System.exit(0);
    }                                       

    private void campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
        if(campo_cpf.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(String.valueOf(campo_senha.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "O campo SENHA é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else{
            
            UsuarioDao uDao = new UsuarioDao();
            
            int x = uDao.entrar(campo_cpf.getText(), String.valueOf(campo_senha.getPassword()));
            
            if(x == 1){
                TelaAcoes tAcoes = new TelaAcoes();
                tAcoes.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "USUARIO NÃO ENCONTRADO, PREENCHA OS CAMPOS CORRETAMENTE", 
                             "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_sair;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelLogin2;
    // End of variables declaration                   
}
