/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import telasAcoes.TelaDepositar;
import telasAcoes.TelaSacar;
import telasAcoes.TelaSaldo;
import telasAcoes.TelaTransferir;

/**
 *
 * @author LENOVO
 */
public class TelaAcoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaAcoes
     */
    public TelaAcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_depositar = new javax.swing.JButton();
        bt_saldo = new javax.swing.JButton();
        bt_transferir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_sacar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bt_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de caixa eletrônico");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(430, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel1.setText("SELECIONE UMA DAS OPÇÕES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        bt_depositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/depositar.png"))); // NOI18N
        bt_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_depositarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_depositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, -1));

        bt_saldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saldo.png"))); // NOI18N
        bt_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saldoActionPerformed(evt);
            }
        });
        getContentPane().add(bt_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, -1));

        bt_transferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transferir.png"))); // NOI18N
        bt_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transferirActionPerformed(evt);
            }
        });
        getContentPane().add(bt_transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("DEPOSITAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("SACAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TRANSFERIR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        bt_sacar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sacar.png"))); // NOI18N
        bt_sacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sacar1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sacar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("SALDO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        pack();
    }// </editor-fold>                        

    private void bt_depositarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        TelaDepositar tSacar = new TelaDepositar();
        tSacar.setVisible(true);
        this.dispose();
    }                                            

    private void bt_saldoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        TelaSaldo tSaldo = new TelaSaldo();
        tSaldo.setVisible(true);
        this.dispose();
    }                                        

    private void bt_transferirActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        TelaTransferir tTransferir = new TelaTransferir();
        tTransferir.setVisible(true);
        this.dispose();
        
    }                                             

    private void bt_sacar1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TelaSacar tSacar = new TelaSacar();
        tSacar.setVisible(true);
        this.dispose();
        
    }                                         

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TelaLogin tLogin = new TelaLogin();
        tLogin.setVisible(true); // mostra a TelaCadastro
        this.dispose(); // fecha a tela de login
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_depositar;
    private javax.swing.JButton bt_sacar1;
    private javax.swing.JButton bt_saldo;
    private javax.swing.JButton bt_transferir;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration                   
}
