/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telasAcoes;

import banco.ConectaBD;
import dao.ContaDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import model.Usuario;
import telas.TelaAcoes;

/**
 *
 * @author LENOVO
 */
public class TelaTransferir extends javax.swing.JFrame {

    /**
     * Creates new form TelaTransferir
     */
    
    private Connection con = ConectaBD.getConexao();
    
    public TelaTransferir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelLogin1 = new javax.swing.JLabel();
        labelLogin2 = new javax.swing.JLabel();
        labelLogin3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campo_cpf_destinatario = new javax.swing.JFormattedTextField();
        campo_cpf_remetente = new javax.swing.JFormattedTextField();
        bt_transferir = new javax.swing.JButton();
        labelLogin4 = new javax.swing.JLabel();
        campo_valor = new javax.swing.JTextField();
        bt_voltar = new javax.swing.JButton();
        campo_senha_remetente = new javax.swing.JPasswordField();
        campo_bancos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de caixa eletroônico");
        setMinimumSize(new java.awt.Dimension(430, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel1.setText("TRANSFERINDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jLabel2.setText("DADOS DO DESTINATARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 2, 14)); // NOI18N
        jLabel3.setText("DADOS DO REMETENTE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        labelLogin1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelLogin1.setText("CPF");
        getContentPane().add(labelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 10));

        labelLogin2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelLogin2.setText("VALOR");
        getContentPane().add(labelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 10));

        labelLogin3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelLogin3.setText("CPF");
        getContentPane().add(labelLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, 10));

        jLabel6.setText("MAX:20");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        try {
            campo_cpf_destinatario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campo_cpf_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, 30));

        try {
            campo_cpf_remetente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campo_cpf_remetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 30));

        bt_transferir.setText("TRANSFERIR");
        bt_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transferirActionPerformed(evt);
            }
        });
        getContentPane().add(bt_transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        labelLogin4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        labelLogin4.setText("SENHA");
        getContentPane().add(labelLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 10));
        getContentPane().add(campo_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 80, 30));

        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));
        getContentPane().add(campo_senha_remetente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, 30));

        campo_bancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Itaú", "Bradesco", "Santander", "Banco do Brasil", "Nubank" }));
        campo_bancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_bancosActionPerformed(evt);
            }
        });
        getContentPane().add(campo_bancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        pack();
    }// </editor-fold>                        

    private void bt_transferirActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
        if(String.valueOf(campo_senha_remetente.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "O campo SENHA é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(campo_valor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo VALOR é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(campo_cpf_remetente.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(campo_cpf_destinatario.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else{
            ContaDao cDao = new ContaDao();
            
            // A FAMOSA GAMBIARRA
            // aqui eu estou fazendo uma pesquisa pra saber se tem algum usuario de destinatario
            int count = 0;
            try{
                Usuario u = new Usuario();
            
                PreparedStatement psPesquisa = con.prepareStatement(
                "SELECT * FROM cadastros");
            
                ResultSet rs = psPesquisa.executeQuery();
                
                while(rs.next()){
                
                u.setIdUsuario(rs.getInt("idUsuario"));
                u.setNome(rs.getString("nome"));
                u.setCpf(rs.getString("cpf"));
                u.setBanco(rs.getString("bancoCliente"));
                u.setSenha(rs.getString("senha"));
                u.setSaldo(rs.getDouble("saldo"));
                    
                    if(u.getCpf().equals(campo_cpf_destinatario.getText()) && u.getBanco().equals(campo_bancos.getSelectedItem().toString())){
                        count = 1;
                        
                        cDao.transferir(
                            campo_cpf_remetente.getText(), 
                            String.valueOf(campo_senha_remetente.getPassword()), 
                            campo_cpf_destinatario.getText(), 
                            campo_bancos.getSelectedItem().toString(), 
                            Double.parseDouble(campo_valor.getText()));
                    }
                }
                
                if(count == 0){
                    JOptionPane.showMessageDialog(null, "USUARIO NÃO ENCONTRADO, PREENCHA OS CAMPOS CORRETAMENTE", 
                             "Aviso", JOptionPane.WARNING_MESSAGE);
                }
                
            }catch(SQLException e){
                System.out.println("Erro:"+e);
            }
        }
    }                                             

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TelaAcoes tAcoes = new TelaAcoes();
        tAcoes.setVisible(true);
        this.dispose();
    }                                         

    private void campo_bancosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTransferir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_transferir;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JComboBox<String> campo_bancos;
    private javax.swing.JFormattedTextField campo_cpf_destinatario;
    private javax.swing.JFormattedTextField campo_cpf_remetente;
    private javax.swing.JPasswordField campo_senha_remetente;
    private javax.swing.JTextField campo_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelLogin2;
    private javax.swing.JLabel labelLogin3;
    private javax.swing.JLabel labelLogin4;
    // End of variables declaration                   
}
