/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telasAcoes;

import dao.ContaDao;
import javax.swing.JOptionPane;
import telas.TelaAcoes;

/**
 *
 * @author LENOVO
 */
public class TelaDepositar extends javax.swing.JFrame {

    /**
     * Creates new form TelaSacar
     */
    public TelaDepositar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_cpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        campo_senha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        bt_depositar = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campo_valor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIstema de caixa eletrônico");
        setMinimumSize(new java.awt.Dimension(430, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel1.setText("DEPOSITANDO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        try {
            campo_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campo_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("VALOR:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 30));

        jLabel6.setText("MAX:20");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        bt_depositar.setText("DEPOSITAR");
        bt_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_depositarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_depositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("SENHA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        campo_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_valorActionPerformed(evt);
            }
        });
        getContentPane().add(campo_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, 30));

        pack();
    }// </editor-fold>                        

    private void campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:

    }                                           

    private void bt_depositarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        // VAI TER QUE VERIFICAR SE TEM OS CAMPOS NA BASE DE DADOS
        
        if(String.valueOf(campo_senha.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "O campo SENHA é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }
        
        else if(campo_cpf.getText().equals("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }else if(campo_valor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo VALOR é obrigatorio, por favor preencher.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
            
            ContaDao conta = new ContaDao();
            
            conta.deposito(
                    campo_cpf.getText(), String.valueOf(campo_senha.getPassword()), Double.parseDouble(campo_valor.getText()));
            
            
        }
        
    }                                            

    private void campo_valorActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        TelaAcoes tAcoes = new TelaAcoes();
        tAcoes.setVisible(true);
        this.dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDepositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_depositar;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JTextField campo_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration                   
}
